# Default colors
[colors.primary]
background = '#282c34'
foreground = '#dcdfe4'

[colors.cursor]
text = '#282c34'
cursor = '#dcdfe4'

# Normal colors
[colors.normal]
black   = '#282c34'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#dcdfe4'

# Bright colors
[colors.bright]
black   = '#282c34'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#dcdfe4'

[font.bold]
family = "MesloLGS Nerd Font"

[font.bold_italic]
family = "MesloLGS Nerd Font"

[font.italic]
family = "MesloLGS Nerd Font"

[font.normal]
family = "MesloLGS Nerd Font"
